# Generated by Django 4.1 on 2022-08-21 23:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_categoria_notice_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
